Add bot.pod/send! to sync-bucket, closes #22
The patch wraps part of the sync-bucket code that does the syncing so that it does not throw
java.lang.RuntimeException: Method code too large! anymore.